name: Build
on: [push, pull_request]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\Activate.ps1
          venv\Scripts\python -m pip install -r requirements.txt

      - name: Build
        run: |
          venv\Scripts\Activate.ps1
          python setup.py -b

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Reports-windows.TGPlugin
          path: dist\Reports.TGPlugin.zip

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          python3 -m pip install -r requirements.txt

      - name: Build
        run: |
          source venv/bin/activate
          python3 setup.py -b

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Reports-linux.TGPlugin
          path: dist/Reports.TGPlugin.zip

  build-macos:
    name: Build for macOS
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          python3 -m pip install -r requirements.txt

      - name: Build
        run: |
          source venv/bin/activate
          python3 setup.py -b

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Reports-macos.TGPlugin
          path: dist/Reports.TGPlugin.zip
